### PR TITLE
Modify TTY device name due to issue in Neovim 0.9

### PR DESCRIPTION
**Pull request by speelbarrow**
See https://neovim.discourse.group/t/writefile-to-dev-tty-stopped-working-in-nvim-0-9/3784/2.

### CODE REVIEW

**Comment by speelbarrow** [comment]
For context -- I figured out that, while it seems the `:!` commands are not being run in a `tty`, the `:terminal` command still gets one, which seems to consistently be `/dev/ttys000`. Replacing the `/dev/tty` in the `WriteTTY` function with `/dev/ttys000` seems to have fixed the issue (for me).

**Comment by speelbarrow** [comment]
Added another commit because I figured out a better fix -- instead of using `/dev/ttys000`, use `/dev/fd/1` because that will always be sure to be stdout

**Comment by eth-p** [comment]
Thanks for the contribution! I don't have a touchbar Mac to test with anymore, but I'd be happy to merge these changes anyways!

If it's not too much trouble, could you tell me if everything still works under regular `vim` with these changes?

**Comment by speelbarrow** [comment]
Thanks for the response! Just checked in a fresh setup (running in a Docker container, passing through the environment variable `ITERM_SESSION_ID`), it works with regular Vim.

**Comment by eth-p** [comment]
Awesome, thanks! Merged!

**Pull request merged**
